apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ba-cicd-pipeline
spec:
  workspaces:
  - name: maven-local-repo
  - name: maven-settings
  - name: shared-workspace
  params:
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "master"
  - name: maven-repo-url
    type: string
    description: maven repository url
    default: "http://nexus-cicd.apps.cluster.example.com"
  - name: maven-username
    type: string
    description: maven repo username
    default: "admin"
  - name: maven-password
    type: string
    description: maven repo password
    default: "admin123" 
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: prepare
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: fix-repo-permission
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-repo
          workspace: maven-local-repo
    - name: build-kjar
      params:
        - name: NEXUS_REPO
          value: $(params.maven-repo-url)
        - name: MAVEN_PROJECT_CONTEXT_DIR
          value: decisions-showcase
        - name: GOALS
          value:
            - clean
            - install
            - '-DskipTests'
      runAfter:
        - prepare
      taskRef:
        kind: Task
        name: mvn
      workspaces:
        - name: maven-repo
          workspace: maven-local-repo
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    - name: run-tests
      params:
        - name: NEXUS_REPO
          value: $(params.maven-repo-url)
        - name: MAVEN_PROJECT_CONTEXT_DIR
          value: decisions-showcase
        - name: GOALS
          value:
            - test
      runAfter:
        - build-kjar
      taskRef:
        kind: Task
        name: mvn
      workspaces:
        - name: maven-repo
          workspace: maven-local-repo
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    - name: build-service
      params:
        - name: NEXUS_REPO
          value: $(params.maven-repo-url)
        - name: MAVEN_PROJECT_CONTEXT_DIR
          value: business-application-service
        - name: GOALS
          value:
            - package
      runAfter:
        - run-tests
      taskRef:
        kind: Task
        name: mvn
      workspaces:
        - name: maven-repo
          workspace: maven-local-repo
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    - name: build-container-img
      params:
        - name: NEXUS_REPO
          value: $(params.maven-repo-url)
        - name: MAVEN_PROJECT_CONTEXT_DIR
          value: business-application-service
        - name: GOALS
          value: 'oc:build'
      runAfter:
        - build-service
      taskRef:
        kind: Task
        name: mvn-jkube
      workspaces:
        - name: maven-repo
          workspace: maven-local-repo
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    - name: deploy
      params:
        - name: NEXUS_REPO
          value: $(params.maven-repo-url)
        - name: MAVEN_PROJECT_CONTEXT_DIR
          value: business-application-service
        - name: GOALS
          value: 'oc:resource oc:apply'
      runAfter:
        - build-container-img
      taskRef:
        kind: Task
        name: mvn-jkube
      workspaces:
        - name: maven-repo
          workspace: maven-local-repo
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
